
let sb=null,products=[],sales=[],customers=[],suppliers=[],orders=[],returnsRows=[];let customerSort={key:null,dir:1};const $=id=>document.getElementById(id);const money=n=>Number(n||0).toLocaleString('ar-LY',{maximumFractionDigits:2})+' د.ل';
function toast(m){let x=document.createElement('div');x.className='toast';x.textContent=m;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
const VERONZA_SUPABASE_URL='https://xmllfoqisxpgzjgxmxng.supabase.co';
const VERONZA_SUPABASE_KEY='sb_publishable_Lg2q4OLoflhhJKVrfPbOew_MAbH-r82';
function cfg(){return {url:VERONZA_SUPABASE_URL,key:VERONZA_SUPABASE_KEY}}
function normalizeSupabaseUrl(raw){let url=String(raw||'').trim().replace(/\/$/,'');let m=url.match(/^https?:\/\/supabase\.com\/dashboard\/project\/([a-z0-9]+)(?:\/.*)?$/i);if(m)url='https://'+m[1]+'.supabase.co';return url}
function saveConfig(){location.reload()}
function showView(id){document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.v===id));document.querySelectorAll('.vp-bottom-nav button[data-v]').forEach(x=>x.classList.toggle('active',x.dataset.v===id));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='orders')renderOrders();if(id==='returns')renderReturns();if(id==='customers')renderCustomers()}
let realtimeChannel=null,loadTimer=null,loadingAll=false;
function scheduleLoadAll(){clearTimeout(loadTimer);loadTimer=setTimeout(()=>loadAll(),350)}
function startRealtime(){if(!sb||realtimeChannel)return;realtimeChannel=sb.channel('veronza-live').on('postgres_changes',{event:'*',schema:'public',table:'products'},scheduleLoadAll).on('postgres_changes',{event:'*',schema:'public',table:'sales'},scheduleLoadAll).on('postgres_changes',{event:'*',schema:'public',table:'customers'},scheduleLoadAll).on('postgres_changes',{event:'*',schema:'public',table:'suppliers'},scheduleLoadAll).on('postgres_changes',{event:'*',schema:'public',table:'orders'},scheduleLoadAll).on('postgres_changes',{event:'*',schema:'public',table:'returns'},scheduleLoadAll).subscribe(status=>{if(status==='SUBSCRIBED')toast('تم تفعيل التحديث المباشر');if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')console.warn('Realtime status:',status)})}
function stopRealtime(){if(realtimeChannel&&sb){sb.removeChannel(realtimeChannel)}realtimeChannel=null}
function makeSupabaseClient(c){return window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,experimental:{passkey:true}}})}
async function registerVeronzaPasskey(){try{if(!sb)throw Error('سجّل الدخول أولاً');if(!window.PublicKeyCredential||!navigator.credentials)throw Error('هذا الجهاز/المتصفح لا يدعم Passkey');let {data,error}=await sb.auth.registerPasskey({friendlyName:'Veronza Face ID'});if(error)throw error;toast('تم تفعيل Face ID لهذا الحساب');return {ok:true,data}}catch(e){console.error(e);toast('تعذر تفعيل Face ID: '+(e.message||'خطأ'));return {ok:false,error:e}}}
async function passkeyLogin(silent=false){try{if(!window.PublicKeyCredential||!navigator.credentials){if(!silent)$('loginMsg').textContent='هذا الجهاز/المتصفح لا يدعم Passkey';return false}let c=cfg();sb=makeSupabaseClient(c);let {data,error}=await sb.auth.signInWithPasskey();if(error)throw error;if(!data?.session)throw Error('لم يتم إنشاء جلسة الدخول');$('login').style.display='none';startRealtime();await loadAll();toast('تم الدخول بـ Face ID بنجاح');return true}catch(e){console.error(e);if(!silent)$('loginMsg').textContent='تعذر الدخول بـ Face ID: '+(e.message||'حاول مرة أخرى');return false}}
async function ensurePasskeyButton(){try{if(sb?.auth?.passkey?.list){const {data}=await sb.auth.passkey.list();const count=Array.isArray(data?.passkeys)?data.passkeys.length:(Array.isArray(data)?data.length:0);if(count>0)localStorage.setItem('veronza_passkey_registered','1')}}catch(e){console.debug('Passkey status check skipped',e)}let c=document.getElementById('vzRegisterPasskeyCard');if(c)c.style.display=''}
async function boot(){let c=cfg();if(!c){$('setup').style.display='flex';return}try{sb=makeSupabaseClient(c);sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){stopRealtime();location.reload()}else if(event==='SIGNED_IN'&&session){$('login').style.display='none';startRealtime();scheduleLoadAll()}});let {data:{session},error:sessionError}=await sb.auth.getSession();if(sessionError)throw sessionError;if(!session){$('login').style.display='flex';return}ensurePasskeyButton();document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showView(b.dataset.v));let u=document.querySelector('.user');u.innerHTML='مرحباً بك <b>'+((session.user.email||'').split('@')[0])+' ⌄</b>';u.onclick=()=>sb.auth.signOut();await loadAll();startRealtime();ensurePasskeyButton()}catch(e){console.error(e);$('setup').style.display='flex';toast('تعذر الاتصال بـ Supabase: '+(e.message||'خطأ غير معروف'))}}
async function login(){try{let c=cfg();if(!c)throw Error('إعداد Supabase غير موجود');sb=makeSupabaseClient(c);let {error}=await sb.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});$('loginMsg').textContent=error?error.message:'تم الدخول';if(!error)location.reload()}catch(e){$('loginMsg').textContent=e.message||'تعذر تسجيل الدخول'}}
async function signup(){try{let c=cfg();if(!c)throw Error('إعداد Supabase غير موجود');sb=makeSupabaseClient(c);let {error}=await sb.auth.signUp({email:$('loginEmail').value.trim(),password:$('loginPassword').value});$('loginMsg').textContent=error?error.message:'تم إنشاء الحساب. تحقق من البريد إذا طلب منك ذلك.'}catch(e){$('loginMsg').textContent=e.message||'تعذر إنشاء الحساب'}}
async function fetchAllRows(table,orderColumn='created_at'){const pageSize=1000;let all=[];for(let from=0;;from+=pageSize){let q=sb.from(table).select('*').order(orderColumn,{ascending:false});if(orderColumn!=='id')q=q.order('id',{ascending:false});const {data,error}=await q.range(from,from+pageSize-1);if(error)throw error;const rows=data||[];all.push(...rows);if(rows.length<pageSize)break}return all}
async function loadAll(){if(!sb||loadingAll)return;loadingAll=true;try{let tables=['products','sales','customers','suppliers','orders','returns'];let results=await Promise.allSettled(tables.map(t=>fetchAllRows(t)));let names=['المنتجات','المبيعات','العملاء','الموردون','الطلبات','المرتجعات'],sets=[v=>products=v,v=>sales=v,v=>customers=v,v=>suppliers=v,v=>orders=v,v=>returnsRows=v];let errors=[];results.forEach((r,i)=>{if(r.status==='fulfilled'){sets[i](r.value||[])}else{errors.push(names[i]+': '+(r.reason?.message||'خطأ في القراءة'))}});renderAll();if(errors.length)toast('تعذر تحديث '+errors.join('، '))}catch(e){console.error(e);toast('تعذر تحديث البيانات: '+(e.message||'خطأ غير معروف'))}finally{loadingAll=false}}
async function generateSequentialBarcode(){if(!sb)throw Error('سجّل الدخول أولاً');const pageSize=1000;let used=new Set();for(let from=0;;from+=pageSize){const {data,error}=await sb.from('products').select('barcode').range(from,from+pageSize-1);if(error)throw error;const rows=data||[];rows.forEach(x=>{const code=String(x.barcode||'').trim();if(code)used.add(code)});if(rows.length<pageSize)break}let max=0;used.forEach(code=>{if(/^\d{6}$/.test(code))max=Math.max(max,Number(code))});let next=max+1;while(used.has(String(next).padStart(6,'0')))next++;if(next>999999)throw Error('تم الوصول إلى الحد الأقصى للباركود المتسلسل');return String(next).padStart(6,'0')}
async function addProduct(){let p={name:$('pName').value.trim(),model:$('pModel').value.trim(),size:$('pSize').value.trim(),color:$('pColor').value.trim(),buy:+$('pBuy').value||0,sell:+$('pSell').value||0,qty:+$('pQty').value||0,min:+$('pMin').value||2};if(!p.name)return toast('اكتب اسم المنتج');for(let attempt=0;attempt<3;attempt++){try{p.barcode=await generateSequentialBarcode();let {error}=await sb.from('products').insert(p);if(!error){['pName','pModel','pSize','pColor','pBuy','pSell','pQty'].forEach(id=>$(id).value='');toast('تمت إضافة المنتج — الباركود '+p.barcode);await loadAll();return}if(error.code!=='23505')return toast(error.message)}catch(e){if(attempt===2)return toast('تعذر إضافة المنتج: '+(e.message||'خطأ'))}}toast('تعذر حجز باركود متسلسل. حاول مرة أخرى')}
async function delProduct(id){if(!confirm('حذف المنتج؟'))return;let {error}=await sb.from('products').delete().eq('id',id);if(error)toast(error.message);else await loadAll()}
function printBarcode(id){let p=products.find(x=>x.id===id);if(!p)return;let w=window.open('','_blank');if(!w)return toast('اسمح بفتح النوافذ المنبثقة للطباعة');w.document.write('<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>Veronza - '+p.barcode+'</title><style>body{font-family:Arial;text-align:center;padding:20px}.brand{font-size:22px;font-weight:bold}.code{font-size:28px;letter-spacing:4px;margin:12px}.meta{font-size:14px}</style></head><body><div class="brand">Veronza</div><div>'+String(p.name).replace(/[<>]/g,'')+'</div><div class="code">'+p.barcode+'</div><div class="meta">'+(p.size||'')+' '+(p.color||'')+'</div></body></html>');w.document.close()}
function renderProducts(){let q=($('productSearch')?.value||'').toLowerCase();let a=products.filter(p=>Object.values(p).join(' ').toLowerCase().includes(q));$('productRows').innerHTML=a.length?a.map(p=>`<tr><td><b>${p.barcode}</b></td><td>${p.name}</td><td>${p.model||''}</td><td>${p.size||''}</td><td>${p.color||''}</td><td class="${p.qty<=p.min?'low':''}">${p.qty}</td><td>${money(p.buy)}</td><td>${money(p.sell)}</td><td><button onclick="printBarcode(${p.id})">طباعة</button> <button class="danger" onclick="delProduct(${p.id})">حذف</button></td></tr>`).join(''):`<tr><td colspan="9" class="empty">لا توجد منتجات</td></tr>`}
async function sell(){let bc=$('saleBarcode').value.trim(),q=+$('saleQty').value||1;if(!bc)return toast('أدخل أو امسح الباركود');let {data,error}=await sb.rpc('record_sale',{p_barcode:bc,p_qty:q,p_customer:$('saleCustomer').value.trim()||null});if(error)return toast(error.message);$('saleBarcode').value='';$('saleQty').value=1;$('saleCustomer').value='';toast('تم تسجيل البيع '+money(data.total));await loadAll()}
async function addCustomer(){let name=$('cName').value.trim();if(!name)return toast('اكتب اسم العميل');let {error}=await sb.from('customers').insert({name,phone:$('cPhone').value.trim(),address:$('cAddress').value.trim(),notes:$('cNotes').value.trim()});if(error)toast(error.message);else{['cName','cPhone','cAddress','cNotes'].forEach(id=>$(id).value='');toast('تمت إضافة العميل');await loadAll()}}
async function addSupplier(){let name=$('sName').value.trim();if(!name)return toast('اكتب اسم المورد');let {error}=await sb.from('suppliers').insert({name,phone:$('sPhone').value.trim()});if(error)toast(error.message);else{['sName','sPhone'].forEach(id=>$(id).value='');toast('تمت إضافة المورد');await loadAll()}}
let orderBusy=false;
function getOrderDisplayList(){return [...orders].sort((a,b)=>{const da=new Date(a.created_at||0).getTime(),db=new Date(b.created_at||0).getTime();if(da!==db)return da-db;return Number(a.id||0)-Number(b.id||0)})}
async function addOrder(){if(orderBusy)return;let customer=$('oCustomer').value.trim(),phone=$('oPhone').value.trim(),address=$('oAddress').value.trim(),total=+$('oTotal').value||0;if(!customer)return toast('اكتب اسم العميل أولاً');if(!phone)return toast('اكتب رقم الهاتف أولاً');orderBusy=true;let btn=document.querySelector('button[onclick="addOrder()"]');if(btn)btn.disabled=true;try{let row={customer,phone,address,total,status:$('oStatus').value||'جديد',delivery_status:$('oDelivery').value||'قيد التجهيز',notes:$('oNotes').value.trim()};let {data,error}=await sb.from('orders').insert(row).select('order_no').single();if(error)throw error;let createdOrderNo=String(data?.order_no||'').trim();if(!createdOrderNo)throw Error('تم إنشاء الطلب لكن تعذر قراءة رقم الطلب');['oNo','oCustomer','oPhone','oAddress','oTotal','oNotes'].forEach(id=>$(id).value='');$('oStatus').value='جديد';$('oDelivery').value='قيد التجهيز';toast('تمت إضافة الطلب رقم '+createdOrderNo);await loadAll()}catch(e){toast(e.message||'تعذر إضافة الطلب')}finally{orderBusy=false;if(btn)btn.disabled=false}}
async function updateOrder(id,field,value){let patch={};patch[field]=value;let {error}=await sb.from('orders').update(patch).eq('id',id);if(error)toast(error.message);else{toast('تم تحديث الطلب');await loadAll()}}
async function deleteOrder(id){if(!confirm('حذف الطلب؟'))return;let {error}=await sb.from('orders').delete().eq('id',id);if(error)toast(error.message);else{toast('تم حذف الطلب');await loadAll()}}
async function addReturn(){let bc=$('rBarcode').value.trim(),q=+$('rQty').value||1;if(!bc)return toast('أدخل أو امسح الباركود');if(q<=0)return toast('الكمية غير صحيحة');let {data,error}=await sb.rpc('record_return',{p_barcode:bc,p_qty:q,p_customer:$('rCustomer').value.trim()||null,p_reason:$('rReason').value.trim()||null});if(error)return toast(error.message);['rBarcode','rCustomer','rReason'].forEach(id=>$(id).value='');$('rQty').value=1;toast('تم تسجيل المرتجع وإرجاع الكمية');await loadAll()}
function sortCustomers(key){if(customerSort.key===key)customerSort.dir*=-1;else{customerSort.key=key;customerSort.dir=1}renderCustomers()}
function renderCustomers(){let q=($('customerSearch')?.value||'').toLowerCase();let a=customers.filter(c=>Object.values(c).join(' ').toLowerCase().includes(q));if(customerSort.key)a.sort((x,y)=>{let av=x[customerSort.key],bv=y[customerSort.key];if(customerSort.key==='last_purchase_at'){av=av?new Date(av).getTime():0;bv=bv?new Date(bv).getTime():0}else{av=Number(av||0);bv=Number(bv||0)}return(av-bv)*customerSort.dir});$('customerRows').innerHTML=a.length?a.map(c=>`<tr><td>${c.name||''}</td><td>${c.phone||''}</td><td>${c.orders||0}</td><td>${money(c.total_purchases)}</td><td>${c.last_purchase_at?new Date(c.last_purchase_at).toLocaleString('ar-LY'):''}</td></tr>`).join(''):`<tr><td colspan="5" class="empty">لا يوجد عملاء</td></tr>`}
function renderOrders(){let a=getOrderDisplayList();$('orderRows').innerHTML=a.length?a.map(o=>{let delivery=o.delivery_status==='pending'?'قيد التجهيز':(o.delivery_status||'قيد التجهيز');return `<tr><td><b>${o.order_no||''}</b></td><td>${o.customer||''}</td><td>${o.phone||''}</td><td>${o.address||''}</td><td>${money(o.total)}</td><td><select onchange="updateOrder(${o.id},'status',this.value)"><option ${o.status==='جديد'?'selected':''}>جديد</option><option ${o.status==='مؤكد'?'selected':''}>مؤكد</option><option ${o.status==='ملغي'?'selected':''}>ملغي</option></select></td><td><select onchange="updateOrder(${o.id},'delivery_status',this.value)"><option value="قيد التجهيز" ${delivery==='قيد التجهيز'?'selected':''}>قيد التجهيز</option><option value="خرج للتوصيل" ${delivery==='خرج للتوصيل'?'selected':''}>خرج للتوصيل</option><option value="تم التسليم" ${delivery==='تم التسليم'?'selected':''}>تم التسليم</option></select></td><td>${o.notes||''}</td><td><button class="danger" onclick="deleteOrder(${o.id})">حذف</button></td></tr>`}).join(''):`<tr><td colspan="9" class="empty">لا توجد طلبات</td></tr>`}
function renderReturns(){let a=[...returnsRows].sort((x,y)=>new Date(y.created_at)-new Date(x.created_at));$('returnRows').innerHTML=a.length?a.map(r=>`<tr><td>${new Date(r.created_at).toLocaleString('ar-LY')}</td><td>${r.barcode||''}</td><td>${r.product||''}</td><td>${r.qty||0}</td><td>${money(r.total)}</td><td>${r.customer||''}</td><td>${r.reason||''}</td></tr>`).join(''):`<tr><td colspan="7" class="empty">لا توجد مرتجعات</td></tr>`}
function clearCustomerFilters(){if($('customerSearch'))$('customerSearch').value='';customerSort={key:null,dir:1};renderCustomers()}
function renderReports(){let range=$('reportRange')?.value||'all',now=new Date(),a=sales.filter(s=>{let d=new Date(s.created_at);if(range==='today')return d.toDateString()===now.toDateString();if(range==='7')return(now-d)<=7*86400000;if(range==='month')return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();return true});let total=a.reduce((x,s)=>x+Number(s.total||0),0),profit=a.reduce((x,s)=>x+Number(s.profit||0),0),qty=a.reduce((x,s)=>x+Number(s.qty||0),0);$('rTotal').textContent=money(total);$('rProfit').textContent=money(profit);$('rQty').textContent=qty.toLocaleString('ar-LY');$('rAvg').textContent=money(a.length?total/a.length:0);$('rInventoryCost').textContent=money(products.reduce((x,p)=>x+Number(p.buy||0)*Number(p.qty||0),0));$('rPotential').textContent=money(products.reduce((x,p)=>x+Number(p.sell||0)*Number(p.qty||0),0));let top={};a.forEach(s=>{let k=s.product||s.barcode||'غير معروف';top[k]=(top[k]||0)+Number(s.qty||0)});let rows=Object.entries(top).sort((x,y)=>y[1]-x[1]).slice(0,20);$('reportRows').innerHTML=rows.length?rows.map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join(''):`<tr><td colspan="2" class="empty">لا توجد مبيعات</td></tr>`}
function renderAll(){renderProducts();renderOrders();renderReturns();renderCustomers();renderReports();let low=products.filter(p=>Number(p.qty||0)<=Number(p.min||0));$('lowStock').innerHTML=low.length?low.map(p=>`<div class="low-item"><b>${p.name}</b><span>${p.qty} متبقي</span></div>`).join(''):'<div class="empty">لا توجد تنبيهات</div>';let totalSales=sales.reduce((a,s)=>a+Number(s.total||0),0);$('dashSales').textContent=money(totalSales);$('dashProducts').textContent=products.length.toLocaleString('ar-LY');$('dashOrders').textContent=orders.length.toLocaleString('ar-LY');$('dashProfit').textContent=money(sales.reduce((a,s)=>a+Number(s.profit||0),0))}
function exportData(){let blob=new Blob([JSON.stringify({products,sales,customers,suppliers,orders,returns:returnsRows},null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='veronza-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.addEventListener('beforeunload',()=>stopRealtime());
boot();
